### ISSUE TITLE
question: is it possible to also remove the non-token characters?

### ISSUE THREAD

**Issue by retorquere** [overview/overview-js-tokenizer#1]
So is there a way to get from `"The cat's meowed 1,000 times! Really!"` to `[ "The", " ", "cat's", " " , "meowed", " ", "1,000", "!", "times", "Really", "!" ]`

**Comment by adamhooper** [comment]
There's no _technical_ difficulty, but I'm finding it hard to imagine this functionality in an intuitive API -- I don't understand where you'd use it. Could you please expound?

In the meantime, I suggest you fork this project. Just change the `\\w` to `.` on this line: https://github.com/overview/overview-js-tokenizer/blob/da59e0fdb1f45ef40e81884b61f3bf86f7466f94/src/tokenize.cc#L30 and run `node-gyp build`.

**Comment by retorquere** [comment]
I need to titlecase strings. Thanks for the hint, I'll look into it.

**Comment by retorquere** [comment]
One possible way to detectably return the results without complicating the api would be to return one as strings, and the other as String objects in the array.

**Comment by adamhooper** [comment]
If you're just looking to title-case Strings, this library is the wrong way to do it.

The thing with title-casing Strings is that there's no agreed-upon solution. Different people have different ideas of what a correct answer is.

The problem with overview-js-tokenizer is that it locks you to a certain logic. Over time, you're going to want to change your capitalization algorithm. But overview-js-tokenizer's logic won't change: it implements "Unicode® Standard Annex #29" exactly.

I suggest you start with a few test strings, and the the following JavaScript:

``` javascript
function titleCaseString(s) {
  return s.charAt(0).toUpperCase() + s.slice(1).replace(/ \w/g, function(m) { return m.toUpperCase(); });
}
```

**Comment by retorquere** [comment]
I'm going to do the title casing myself (my target is BibLaTeX, and only for English, so there is a rough specification of what to do), but I need to break up a string into words. `\w` is not unicode-safe, alas. Annex 29 is exactly what I'm looking for. I'm currently working on a state-transition based solution working from http://www.unicode.org/Public/6.2.0/ucd/auxiliary/WordBreakTest.html, but if someone has already done the work, I'm not complaining.

**Comment by adamhooper** [comment]
If you're bent on using word segmentation, I recommend you fork this project and make the change I suggested above.

Or even better: if you can stomach C++, use ICU directly. (Read overview-js-tokenizer's `tokenize.cc` for inspiration.) ICU gives you character offsets as described in tr29. (The web page you refer to is derived from tr29.)

Beware the issues you'll face:
- tr29 will separate hyphenated words, e.g., `out-of-the-box`, into four separate words. You probably only want to capitalize the first.
- tr29 will keep apostrophes together, e.g., `o'neil`. You want to capitalize both.
- You probably don't want to capitalize `a`, `of`, et cetera.

Title casing is impossible to get "right", because there _is_ no "right". Regardless of your implementation, you're going to make assumptions about your input (easy, if it's English book titles) and you're going to create a set of rules particular to those assumptions. The output will contain obvious errors; you'll fix most and maybe leave a few behind.

If you _do_ end up implementing tr29, I'll bet at the end of the project you'll look back and think, "I could have just used regexes."

**Comment by retorquere** [comment]
I'm open to using regexes. I just haven't been able to get them to work to satisfaction, even for relatively simple cases; given `this ain't 'America'`, I want to see `this`, `ain't` and `America` as words.

I hadn't spotted this was C-based. I have no beef with C, but I need to use this in a Firefox extension, so I'm looking for a pure-JS tokenizer.

**Comment by retorquere** [comment]
(I'm aware that doing title casing perfectly is a fool's errand, but it only needs to be good, not perfect, and exclusively for english titles)

**Comment by adamhooper** [comment]
@retorquere A previous version of this library used pure JS, so you may want to clone the repository and revert a ways.

Other than that, I'm closing this issue: in my view, it's missing a concrete use case or API suggestion. I'm not opposed to the idea in general; I'm just opposed to leaving open an issue open without a clear path to closing it.

**Comment by retorquere** [comment]
Sure. Can you point (roughly) into the history where i could find this?

**Comment by adamhooper** [comment]
https://github.com/overview/overview-js-tokenizer/commits/master

**Comment by adamhooper** [comment]
For future searchers: I've created https://github.com/huffpostdata/node-word-boundaries, which is a lower-level implementation that does (almost) exactly what the poster asked for.
